# Generated by Django 4.1.7 on 2023-03-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
