# Generated by Django 4.1.7 on 2023-03-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Mid'), (3, 'High'), (4, 'Top')], default='Low', max_length=50),
        ),
    ]
