# Generated by Django 4.1.7 on 2023-03-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_note_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='preferred_weather',
            field=models.CharField(blank=True, choices=[('Cold (below 0°C)', 'Cold (below 0°C)'), ('Moderate (0-15°C)', 'Moderate (0-15°C)'), ('Warm (16°C +)', 'Warm (16°C +)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Top', 'Top')], default='Low', max_length=50),
        ),
    ]
