# Generated by Django 4.1.7 on 2023-03-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_note_preferred_weather_alter_note_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='preferred_weather',
            field=models.IntegerField(blank=True, choices=[(1, 'Cold (below 0°C)'), (2, 'Moderate (0-15°C)'), (3, 'Warm (16°C +)')]),
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Mid'), (3, 'High'), (4, 'Top')], default=1),
        ),
    ]
