# Generated by Django 4.1.7 on 2023-03-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_alter_note_preferred_weather_alter_note_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Mid'), (3, 'High')], default='Low'),
        ),
    ]
